[project]
name = "micrograd-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.3.3",
    "matplotlib>=3.9.3",
    "numpy>=2.2.0",
]
